version: '3.8'
services:
 
  db_bike:
    image: postgres:13
    container_name: db_bike_renting
    environment:
      POSTGRES_USER: rileone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bike_renting
    ports:
      - "5433:5432"
    volumes:
      - db_bike:/var/lib/postgresql/data
    networks:
      - express_network
  db_hotel:
    image: postgres:13
    container_name: db_hotel_booking
    environment:
      POSTGRES_USER: rileone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_booking
    ports:
      - "5434:5432"
    volumes:
      - db_hotel:/var/lib/postgresql/data
    networks:
      - express_network
  db_money:
    image: postgres:13
    container_name: db_money_confirmation
    environment:
      POSTGRES_USER: rileone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: money_confirmation
    ports:
      - "5435:5432"
    volumes:
      - db_money:/var/lib/postgresql/data
    networks:
      - express_network
  db_order_management:
    image: postgres:13
    container_name: db_order_management
    environment:
      POSTGRES_USER: rileone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_management
    ports:
      - "5436:5432"
    volumes:
      - db_order_management:/var/lib/postgresql/data
    networks:
      - express_network

volumes:
  db_order_management:
  db_bike:
  db_hotel:
  db_money:

networks:
  express_network:
