networks:
  app_network:

#TODO_PROD: uncomment in production
# volumes:
  # db_bike_rental:
  #   driver: local
  # db_order_management:
  # db_hotel_booking:
  # db_payment:

services:

  bike-rental-service:
    build: ./src/backend/bike-rental
    tty: true
    environment:
    #TODO_PROD: update in "production"
      - NODE_ENV=development #enabling more verbose logging, using development-specific configurations, or enabling hot-reloading
      - POSTGRES_DB=bike_rental
      - POSTGRES_USER=rileone
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgres://rileone:password@db_bike_rental:5432/bike_rental
    command: >
      sh -c "npm install \
      && npx prisma generate --schema ./src/prisma/schema.prisma \
      && npx tsx src/index.ts"
    #TODO_PROD: remove in production
    volumes:
      - ./src/backend/bike-rental:/app
      - ./src/backend/bike-rental/package.json:/app/package.json
      # - /app/node_modules
    depends_on:
      - db_bike_rental
    networks:
      - app_network
    #TODO_PROD: update to serve only in the internal network
    ports:
      - "3000:3000"
    # expose:
    #   - "3000"

  hotel-booking-service:
    build: ./src/backend/hotel-booking
    environment:
      - NODE_ENV=development
      - POSTGRES_DB=hotel_booking
      - POSTGRES_USER=rileone
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgres://rileone:password@db_hotel_booking:5432/hotel_booking
    command: >
      sh -c "npm install \
      && npx prisma generate --schema ./prisma/schema.prisma \
      && npx tsx src/index.ts"
    volumes:
      - ./src/backend/hotel-booking:/app
      - ./src/backend/hotel-booking/package.json:/app/package.json
    depends_on:
      - db_hotel_booking
    networks:
      - app_network
    ports:
      - "3001:3000"

  payment-service:
    build: ./src/backend/payment
    environment:
      - NODE_ENV=development
      - POSTGRES_DB=payment
      - POSTGRES_USER=rileone
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgres://rileone:password@db_payment:5432/payment
    command: >
      sh -c "npm install \
      && npx prisma generate --schema ./prisma/schema.prisma \
      && npx tsx src/index.ts"
    volumes:
      - ./src/backend/payment:/app
      - ./src/backend/payment/package.json:/app/package.json
    depends_on:
      - db_payment
    networks:
      - app_network
    ports:
      - "3002:3000"
    
  order-management-service:
    build: ./src/backend/order-management
    environment:
      - NODE_ENV=development
      - POSTGRES_DB=order_management
      - POSTGRES_USER=rileone
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgres://rileone:password@db_order_management:5432/order_management
    command: >
      sh -c "npm install \
      && npx prisma generate --schema ./src/prisma/schema.prisma \
      && npx tsx src/index.ts"
    volumes:
      - ./src/backend/order-management:/app
      - ./src/backend/order-management/package.json:/app/package.json
    depends_on:
      - db_order_management
    networks:
      - app_network
    ports:
      - "3003:3000"
  
  db_bike_rental:
    image: postgres:13
    environment:
      - POSTGRES_USER=rileone
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bike_rental
    volumes:
    #TODO_PROD: update to let docker manage the volume
      - ./db_bike_rental:/var/lib/postgresql/data
      - ./src/backend/bike-rental/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    #TODO_PROD: update to serve only in the internal network
    ports:
      - "5433:5432"
    # expose:
    #   - "5432"

  db_hotel_booking:
    image: postgres:13
    environment:
      - POSTGRES_USER=rileone
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hotel_booking
    volumes:
      - ./db_hotel_booking:/var/lib/postgresql/data
      - ./src/backend/hotel-booking/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    ports:
      - "5434:5432"
  
  db_payment:
    image: postgres:13
    container_name: db_payment
    environment:
      POSTGRES_USER: rileone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment
    volumes:
      - ./db_payment:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5435:5432"

  db_order_management:
    image: postgres:13
    container_name: db_order_management
    environment:
      POSTGRES_USER: rileone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_management
    volumes:
      - ./db_order_management:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5436:5432"

  #--------------------------
  #LOGGING AND MONITORING

  #grafana:
  #  image: grafana/grafana:latest
  #  ports:
  #    - 3000:3000
  #  volumes:
  #    - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
  #  environment:
  #    - GF_AUTH_ANONYMOUS_ENABLED=true
  #    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #    - GF_AUTH_DISABLE_LOGIN_FORM=true
  #  networks:
  #    - app_network
#
  #loki:
  #  image: grafana/loki:latest
  #  ports:
  #    - 3100:3100
  #  command: -config.file=/etc/loki/local-config.yaml
  #  networks:
  #    - app_network
#
  #promtail:
  #  image:  grafana/promtail:latest
  #  container_name: promtail
  #  volumes:
  #    - ./config/promtail.yaml:/etc/promtail/docker-config.yaml
  #    - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: -config.file=/etc/promtail/docker-config.yaml
  #  depends_on:
  #    - loki
  #  networks:
  #    - app_network

