version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: db_Order_Management
    environment:
      POSTGRES_USER: rileone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restAPI
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - express_network

volumes:
  postgres_data:

networks:
  express_network:
